### PR TITLE
New Projects added

### PR DESCRIPTION
**Pull request by Pratikshaekbote**

### CODE REVIEW

**Comment by ayushete02** [comment]
@Pratikshaekbote create folder then add files in it

**Comment by ayushete02** [comment]
इस कारण हमारा देश कई देशों से नीचे है

**Comment by Pratikshaekbote** [comment]
Yes sir 🙂

**Comment by Pratikshaekbote** [comment]
Created folders for android Project

**Comment by ayushete02** [comment]
And for other projects?

**Comment by Pratikshaekbote** [comment]
yes they have separate folders

**Pull request merged**
